# Generated by Django 3.0.4 on 2021-09-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0407_emsrfcee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayDetailsExcelupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('Shift', models.CharField(max_length=255, null=True)),
                ('CenterCode', models.CharField(blank=True, max_length=255, null=True)),
                ('MilkType', models.CharField(max_length=255, null=True)),
                ('Good_Sour', models.CharField(blank=True, max_length=255, null=True)),
                ('SampleNo', models.FloatField(blank=True, default=0.0, null=True)),
                ('Cans', models.FloatField(blank=True, default=0.0, null=True)),
                ('Kgs', models.FloatField(default=0.0, null=True)),
                ('Fat', models.FloatField(default=0.0, null=True)),
                ('SNF', models.FloatField(default=0.0, null=True)),
                ('CLR', models.FloatField(default=0.0, null=True)),
                ('TSRATE', models.FloatField(blank=True, default=0.0, null=True)),
                ('Rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('comm', models.FloatField(blank=True, default=0.0, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('payeeBank', models.CharField(max_length=25)),
                ('payAdvRefNo', models.CharField(max_length=50)),
                ('payDate', models.DateField(blank=True, null=True)),
                ('PayAmt', models.FloatField(blank=True, default=0.0, null=True)),
                ('file_name', models.CharField(max_length=22)),
            ],
        ),
    ]
