# Generated by Django 3.2 on 2021-10-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0408_paydetailsexcelupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='active',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='datefrom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='dateto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
