# Generated by Django 3.2 on 2021-10-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0409_auto_20211005_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor1',
            name='datefrom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisor1',
            name='dateto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
