# Generated by Django 3.0.4 on 2021-10-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0411_auto_20211005_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpCode', models.CharField(blank=True, max_length=25, null=True)),
                ('cpName', models.CharField(blank=True, max_length=50, null=True)),
                ('PStDate', models.DateField(blank=True, null=True)),
                ('PEndDate', models.DateField(blank=True, null=True)),
                ('CoupValue', models.FloatField(blank=True, default=0.0, null=True)),
                ('PCode', models.CharField(blank=True, max_length=255, null=True)),
                ('qty_from', models.FloatField(blank=True, default=0.0, null=True)),
                ('qty_to', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custCode', models.CharField(max_length=255, unique=True)),
                ('custName', models.CharField(max_length=255)),
                ('cust_type', models.CharField(blank=True, max_length=255, null=True)),
                ('zoneCode', models.CharField(blank=True, max_length=255, null=True)),
                ('saleExecCode', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=225, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='centerimage')),
                ('bankacctno', models.CharField(blank=True, max_length=255, null=True)),
                ('acctholdername', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=255, null=True)),
                ('bankName', models.CharField(blank=True, max_length=255, null=True)),
                ('bankBranch', models.CharField(blank=True, max_length=255, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('Branchname', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='custType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cTypeCode', models.CharField(max_length=255, unique=True)),
                ('cTypeName', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='daily_sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('custcode', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=255, null=True)),
                ('orderNo', models.IntegerField(default=0)),
                ('custType', models.CharField(blank=True, max_length=15, null=True)),
                ('prodCode', models.CharField(blank=True, max_length=25, null=True)),
                ('quantity', models.FloatField(blank=True, default=0.0, null=True)),
                ('couponCode', models.CharField(blank=True, max_length=25, null=True)),
                ('disc', models.FloatField(blank=True, default=0.0, null=True)),
                ('comm', models.FloatField(blank=True, default=0.0, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('unitRate', models.FloatField(blank=True, default=0.0, null=True)),
                ('netAmount', models.FloatField(blank=True, default=0.0, null=True)),
                ('ZoneCode', models.CharField(blank=True, max_length=255, null=True)),
                ('SaleExecCode', models.CharField(blank=True, max_length=255, null=True)),
                ('remove', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='prodMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PCode', models.CharField(blank=True, max_length=25, null=True)),
                ('PName', models.CharField(blank=True, max_length=50, null=True)),
                ('PStDate', models.DateField(blank=True, null=True)),
                ('PEndDate', models.DateField(blank=True, null=True)),
                ('unitRate', models.FloatField(blank=True, default=0.0, null=True)),
                ('prod_type', models.CharField(blank=True, max_length=255, null=True)),
                ('qty_from', models.FloatField(blank=True, default=0.0, null=True)),
                ('qty_to', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesExec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SEcode', models.CharField(max_length=255, unique=True)),
                ('SEname', models.CharField(blank=True, max_length=255, null=True)),
                ('SEJoinDate', models.DateField(blank=True, null=True)),
                ('SELastDate', models.DateField(blank=True, null=True)),
                ('Zone_attached', models.CharField(max_length=255)),
                ('Zone_attached1', models.CharField(max_length=255)),
                ('Zone_attached2', models.CharField(max_length=255)),
                ('active', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('remove', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zCode', models.CharField(max_length=255, unique=True)),
                ('zName', models.CharField(max_length=255)),
                ('zSt_date', models.DateField(blank=True, null=True)),
                ('zEnd_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('remove', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
