# Generated by Django 3.0.4 on 2021-10-09 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0412_coupon_customer_custtype_daily_sales_prodmaster_salesexec_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Branchname',
            new_name='branch',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='acctholdername',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bankBranch',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bankName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bankacctno',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ifsc',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='photo',
        ),
        migrations.AddField(
            model_name='customer',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='custimage'),
        ),
        migrations.AddField(
            model_name='daily_sales',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createSale', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='daily_sales',
            name='crreatedd',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='daily_sales',
            name='updatedd',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='daily_sales',
            name='upt_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updSale', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prodmaster',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='prodimage'),
        ),
        migrations.CreateModel(
            name='daily_receipts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('orderNo', models.IntegerField(default=0)),
                ('recdate', models.DateField(blank=True, null=True)),
                ('recType', models.CharField(blank=True, max_length=15, null=True)),
                ('payRefNo', models.CharField(blank=True, max_length=25, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('remarks', models.CharField(blank=True, max_length=25, null=True)),
                ('remove', models.CharField(blank=True, max_length=255, null=True)),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createR', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updateR', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
