# Generated by Django 3.2 on 2021-10-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0414_auto_20211011_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_sales',
            name='remarks',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
