# Generated by Django 3.2 on 2021-10-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0415_daily_sales_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodmaster',
            name='active',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prodmaster',
            name='remove',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
