# Generated by Django 3.2 on 2021-10-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0417_prodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodmaster',
            name='custCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
