# Generated by Django 3.2 on 2021-10-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0418_prodmaster_custcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
